# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: main.yml
k8s_backup_location: "{{ backup_location }}/k8s"
file_permission: '0644'
directory_mode: "755"

# Usage: timescaledb.yml
database_name: "telemetry_metrics"
telemetry_namespace: "telemetry-and-visualizations"
timescaledb_k8s_name: timescaledb
timescale_telemetry_backup_file: "telemetry_tsdb_dump.sql"
idrac_telemetry_path: "/go/src/github.com/telemetry-reference-tools/omnia_timescaledb.tar.gz"
postgresql_pod_data: "/var/lib/postgresql/data"
idrac_mnt_tar: "{{ mount_location }}/iDRAC-Telemetry-Reference-Tools/omnia_timescaledb.tar.gz"
file_mode: "0644"

# Usage: mysqldb.yml
mysqldb_k8s_name: mysqldb
mysqldb_local_backup_file: "mysqldb_dump.sql"
mysqldb_name: "idrac_telemetrysource_services_db"
mysql_telemetry_db_backup_file: "idrac_telemetrysource_services_db_backup.sql"

# Usage: etcd.yml
k8s_pip_package: "kubernetes==30.1.0"
etcd_env_file: "/etc/etcd.env"
etcd_file_fail_msg: "Failed. {{ etcd_env_file }} doesn't exist on system. So backup of etcd cannot be performed."
snapshot_db_name: "{{ k8s_backup_location }}/snapshot.db"
etcd_snapshot_save_fail_msg: "Backup of etcd snapshot failed: {{ snapshot_result.stderr }}"
etcd_snapshot_status_fail_msg: "Backup of etcd snapshot status failed: {{ snapshot_status.stderr }}"
manifests_dir: "{{ k8s_backup_location }}/manifests"
shell_script_file: "{{ k8s_backup_location }}/backup.sh"
backup_file_source: "backup.sh"
k8s_backup_location_tarball: "{{ k8s_backup_location }}.tar.gz"
