# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Ping the powervault device to validate connectivity
  ansible.builtin.command: ping -c1 {{ inventory_hostname }}
  register: validate_login
  changed_when: false
  ignore_errors: true

- name: Get auth string
  ansible.builtin.shell: echo -n {{ powervault_username }}_{{ powervault_password }} | sha256sum
  register: auth_string
  changed_when: false
  no_log: true
  ignore_errors: true

- name: Get session key
  ansible.builtin.uri:
    url: https://{{ inventory_hostname }}/api/login/{{ auth_string.stdout | replace(" -", "") }}
    method: GET
    headers:
      {'datatype': 'json'}
    validate_certs: false
  register: sas_session_key

- name: Execute show initiators command
  ansible.builtin.uri:
    url: "https://{{ inventory_hostname }}/api/show/initiators"
    method: GET
    body_format: json
    validate_certs: false
    use_proxy: false
    timeout: "{{ task_timeout }}"
    headers:
      sessionKey: "{{ sas_session_key.json.status[0].response }}"
      datatype: json
    return_content: true
  register: hosts_info

- name: Get all the available IDs
  ansible.builtin.set_fact:
    initiator_ids: "{{ initiator_ids | default([]) + [item.id] }}"
    no_of_vol: "{{ powervault_volumes | length }}"
  loop: "{{ (hosts_info.content | from_json)['initiator'] }}"

- name: Set the LUN nos.
  ansible.builtin.set_fact:
    lun_no: "{{ lun_no | default([]) + [temp1] }}"
    temp1: "{{ temp1 | int + t1 | int }}"
  vars:
    temp1: 0  # Initial value, incremented by t1 during the loop
    t1: 1     # Increment step
  loop: "{{ powervault_volumes }}"

- name: Add the lun numbers to volumes
  ansible.builtin.set_fact:
    pv_volumes: "{{ pv_volumes | default([]) + [{'name': item.0, 'lun_no': item.1}] }}"
  with_together:
    - "{{ powervault_volumes }}"
    - "{{ lun_no }}"

- name: Map volumes to initiators
  ansible.builtin.uri:
    url: >
      https://{{ inventory_hostname }}/api/map/volume/{{ volume.name }}/access/{{ access }}/lun/{{ volume.lun_no }}/initiator/{{ initiator }}
    method: GET
    body_format: json
    validate_certs: false
    use_proxy: false
    headers:
      sessionKey: "{{ sas_session_key.json.status[0].response }}"
      datatype: json
    return_content: true
  loop: "{{ initiator_ids | product(pv_volumes) | list }}"
  vars:
    initiator: "{{ item.0 }}"
    volume: "{{ item.1 }}"
  loop_control:
    label: "{{ volume.name }}"
