server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: varlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: Directory Server Utilization
    static_configs:
      - targets:
          - localhost
        labels:
          job: Directory Server Utilization
          __path__: /var/log/dirsrv/slapd-*/access

  - job_name: Directory Server Errors
    static_configs:
      - targets:
          - localhost
        labels:
          job: Directory Server Errors
          __path__: /var/log/dirsrv/slapd-*/errors

  - job_name: Directory Server Utilization for Leap
    static_configs:
      - targets:
          - localhost
        labels:
          job: Directory Server Utilization
          __path__: /var/log/dirsrv/slapd-ldap1/access

  - job_name: Directory Server Errors for Leap
    static_configs:
      - targets:
          - localhost
        labels:
          job: Directory Server Errors
          __path__: /var/log/dirsrv/slapd-ldap1/errors

  - job_name: PKI Transactions
    static_configs:
      - targets:
          - localhost
        labels:
          job: PKI Transactions
          __path__: /var/log/pki/pki-tomcat/ca/transactions

  - job_name: KDC Utilization
    static_configs:
      - targets:
          - localhost
        labels:
          job: KDC Utilization
          __path__: /var/log/krb5kdc.log

  - job_name: FreeIPA API Call
    static_configs:
      - targets:
          - localhost
        labels:
          job: FreeIPA API Call
          __path__: /var/log/httpd/*

  - job_name: audit
    static_configs:
      - targets:
          - localhost
        labels:
          job: audit
          __path__: /var/log/audit/*log

  - job_name: SSSD
    static_configs:
      - targets:
          - localhost
        labels:
          job: SSSD
          __path__: /var/log/sssd/*log

  - job_name: secure
    static_configs:
      - targets:
          - localhost
        labels:
          job: secure
          __path__: /var/log/secure

  - job_name: Omnia logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: Omnia logs
          __path__: /var/log/omnia.log

  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/messages

  - job_name: cron
    static_configs:
      - targets:
          - localhost
        labels:
          job: cron
          __path__: /var/log/cron

  - job_name: IPA Server and Client
    static_configs:
      - targets:
          - localhost
        labels:
          job: IPA Server and Client
          __path__: /var/log/ipa*log

  - job_name: Package Rocky
    static_configs:
      - targets:
          - localhost
        labels:
          job: Package Rocky
          __path__: /var/log/dnf.log

  - job_name: Package Leap
    static_configs:
      - targets:
          - localhost
        labels:
          job: Package Leap
          __path__: /var/log/zypper.log

  - job_name: k8s pods
    static_configs:
      - targets:
          - localhost
        labels:
          job: k8s pods
          __path__: /var/log/pods/*/*/*log

  - job_name: accelerator logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: accelerator logs
          __path__: /var/log/omnia/accelerator.log

  - job_name: discovery logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: discovery logs
          __path__: /var/log/omnia/discovery.log

  - job_name: local_repo log
    static_configs:
      - targets:
          - localhost
        labels:
          job: local_repo log
          __path__: /var/log/omnia/local_repo.log

  - job_name: kubespray_telemetry logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: kubespray_telemetry logs
          __path__: /var/log/omnia/kubespray_omnia.log

  - job_name: network logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: network logs
          __path__: /var/log/omnia/network.log

  - job_name: platforms logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: platforms logs
          __path__: /var/log/omnia/platforms.log

  - job_name: prepre_cp log
    static_configs:
      - targets:
          - localhost
        labels:
          job: prepre_cp log
          __path__: /var/log/omnia/prepare_cp.log

  - job_name: provision logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: provision logs
          __path__: /var/log/omnia/provision.log

  - job_name: scheduler logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: scheduler logs
          __path__: /var/log/omnia/scheduler.log

  - job_name: security logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: security logs
          __path__: /var/log/omnia/security.log

  - job_name: storage logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: storage logs
          __path__: /var/log/omnia/storage.log

  - job_name: server_spec_update logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: server_spec_update logs
          __path__: /var/log/omnia/server_spec_update.log

  - job_name: telemetry logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: telemetry logs
          __path__: /var/log/omnia/telemetry.log

  - job_name: tools logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: tools logs
          __path__: /var/log/omnia/tools.log

  - job_name: upgrade log
    static_configs:
      - targets:
          - localhost
        labels:
          job: upgrade log
          __path__: /var/log/omnia/upgrade.log

  - job_name: utils logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: utils logs
          __path__: /var/log/omnia/utils.log

  - job_name: utils cluster logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: utils cluster logs
          __path__: /var/log/omnia/utils_cluster.log

  - job_name: ip_rule_assignment logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ip_rule_assignment logs
          __path__: /var/log/omnia/ip_rule_assignment.log

  - job_name: performance_profile logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: performance_profile logs
          __path__: /var/log/omnia/performance_profile.log

  - job_name: software_update logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: software_update logs
          __path__: /var/log/omnia/software_update.log

  - job_name: cluster deployment logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: cluster deployment logs
          __path__: /var/log/xcat/cluster.log*

  - job_name: compute log messages
    static_configs:
      - targets:
          - localhost
        labels:
          job: compute log messages
          __path__: /var/log/xcat/computes.log*

  - job_name: benchmarks log messages
    static_configs:
      - targets:
          - localhost
        labels:
          job: benchmarks log messages
          __path__: /var/log/omnia/benchmarks.log
