# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Update node_name in Omnia db from control_plane to oim
  ansible.builtin.command: |
     {{ python_version }} {{ oim_db_path }}

- name: Update the node details in xcat table site
  ansible.builtin.command: "{{ xcat_bin_path }}/chdef -t site excludenodes=''"
  changed_when: true
  register: set_excludenodes_value

- name: Update the hosts table in the xcat db to remove the entry for control_plane if present
  ansible.builtin.command: "{{ xcat_bin_path }}/chdef -t node -o control_plane -n oim"
  changed_when: true
  register: update_node_entry

- name: Update the hosts table in the xcat db to change the groups column for control_plane if present
  ansible.builtin.command: "{{ xcat_bin_path }}/chdef oim groups=oim"
  changed_when: true
  register: update_group_entry

- name: Update the node details in xcat table site
  ansible.builtin.command: "{{ xcat_bin_path }}/chdef -t site excludenodes={{ oim }}"
  changed_when: true
  register: set_excludenodes_value
